
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Aug 04 14:55:21 EDT 2011
//----------------------------------------------------

package gsd.iml.parser;

/** CUP generated class containing symbol constants. */
public class Token {
  /* terminals */
  public static final int IS_LOADED = 54;
  public static final int LONG_LITERAL = 55;
  public static final int DIVIDE = 44;
  public static final int DISPLAY = 8;
  public static final int STRING_LITERAL = 57;
  public static final int GTEQ = 37;
  public static final int DESCRIPTION = 9;
  public static final int ACTIVE_IF = 18;
  public static final int LTEQ = 35;
  public static final int MINUS_MINUS = 51;
  public static final int DOUBLE_FLOATING_POINT_LITERAL = 56;
  public static final int DEFAULT_VALUE = 17;
  public static final int INTERFACE = 13;
  public static final int BT_XOR = 31;
  public static final int REQUIRES = 19;
  public static final int MINUS = 41;
  public static final int LEGAL_VALUES = 22;
  public static final int COMPONENT = 11;
  public static final int IS_ACTIVE = 47;
  public static final int DATA = 15;
  public static final int NOT = 50;
  public static final int AND = 28;
  public static final int LT = 34;
  public static final int OPTION = 10;
  public static final int IS_SUBSTRING = 48;
  public static final int BT_RIGHT = 39;
  public static final int RPAR = 7;
  public static final int BT_AND = 30;
  public static final int OR = 27;
  public static final int COMMA = 46;
  public static final int BOOL = 16;
  public static final int FLAVOR = 52;
  public static final int IMPLIES = 26;
  public static final int PLUS = 40;
  public static final int ID = 58;
  public static final int DOT = 42;
  public static final int EOF = 0;
  public static final int CALCULATED = 20;
  public static final int UNARY = 59;
  public static final int error = 1;
  public static final int MOD = 45;
  public static final int NEQ = 33;
  public static final int BOOLDATA = 49;
  public static final int EQ = 32;
  public static final int LBRACK = 4;
  public static final int IS_ENABLED = 53;
  public static final int TIMES = 43;
  public static final int NONE = 14;
  public static final int COLON = 25;
  public static final int LBRACE = 2;
  public static final int RBRACK = 5;
  public static final int TO = 23;
  public static final int PACKAGE = 12;
  public static final int BT_OR = 29;
  public static final int RBRACE = 3;
  public static final int LPAR = 6;
  public static final int QUESTION = 24;
  public static final int GT = 36;
  public static final int IMPLEMENTS = 21;
  public static final int BT_LEFT = 38;
}

